### ISSUE TITLE
alarm

### ISSUE THREAD

**Issue by bosshog** [innowatio/iwwa-front#15]
Come Energy Manager, voglio impostare gli allarmi sulla base dei consumi in diretta così da essere notificato in caso un punto di consumo soddisfi i criteri impostati, se l'allarme corrispondente è attivo, e voglio poter filtrare la lista degli allarmi impostati in modo da poter vedere solo quelli a cui sono interessato.
## Acceptance criteria
1. Un Energy Manager accede al sistema e va alla pagina di impostazione allarmi.
2. L'utente seleziona un punto di misura da una lista che riporta tutti i punti, anche di siti differenti e organizzati gerarchicamente (tipo file tree), e imposta l'allarme sui consumi in diretta, specificando la tipologia di allarme (a soglia, on / off) e l'eventuale percentuale di tolleranza in eccesso e / o difetto.
3. L'allarme impostato appare nella lista degli allarmi in stato attivo.
4. L'utente filtra la lista degli allarmi, scegliendo tra quelli attivi / inattivi e tipologia o quelli che hanno generato una notifica negli ultimi 30 giorni.
5. La situazione è critica e l'utente riceve una notifica relativa all'allarme.
6. L'utente agisce sulla notifica e i dettagli dell'evento vengono visualizzati: nome del punto di misura, data / ora, durata dell'evento, costo.
7. L'utente seleziona un link presente nella visualizzazione dei dettagli e l'historical consumptions widget viene visualizzato riportando i dati per il punto di misura che ha generato l'allarme, con indicazione nel grafico del momento temporale per il quale l'allarme è scattato.
8. L'utente torna alla visualizzazione dei dettagli e seleziona un altro link che lo porta alla pagina dei consigli per la tipologia di punto di misura che ha generato l'allarme. I consigli sono inseriti da un amministratore di sistema e sono organizzati per tipologia di punto di misura. Le tipologie di punti di misura sono: ventilazione, condizionamento, illuminazione.

**Comment by pscanf** [comment]
L'allarme è associato al sito, non all'utente.
