### ISSUE TITLE
Definire l'architettura di comunicazione tra database (e sistemi interni) Innowatio e l'app

### ISSUE THREAD

**Issue by pscanf** [innowatio/iwwa-front#44]
References #36

**Comment by fmondora** [comment]
È pensabile usare Amazon SQS?

**Comment by bosshog** [comment]
@pscanf Ho chiesto al responsabile Innowatio per ubuntu sulla macchina virtuale e preferirebbero stare in ambiente windows. Eventualmente, chiedono se potrebbe andar bene Linux CentOS
